import ExcelJS from "exceljs";

const EXCEL_EXPORT_FILE = "products-export.xlsx";
const TEMPLATE_FILE = "products-import-template.xlsx";
const VALID_CATEGORIES = ["Dog Food", "Cat Food", "Accessories", "Pet Toys", "Medicine"];
const VALID_STATUSES = ["ACTIVE", "INACTIVE", "OUT_OF_STOCK"];

const normalizeCategory = (value) => String(value ?? "").trim();
const normalizeStatus = (value) => String(value ?? "").trim().toUpperCase();

function formatCurrency(value) {
  const num = Number(value);
  return Number.isFinite(num) ? num : 0;
}

function createHeaderStyle(workbook) {
  return {
    font: { bold: true, color: { argb: "FFFFFFFF" } },
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FF2563EB" } },
    alignment: { horizontal: "center", vertical: "middle" },
    border: {
      top: { style: "thin", color: { argb: "FFCBD5E1" } },
      left: { style: "thin", color: { argb: "FFCBD5E1" } },
      bottom: { style: "thin", color: { argb: "FFCBD5E1" } },
      right: { style: "thin", color: { argb: "FFCBD5E1" } },
    },
  };
}

function createInstructionRows() {
  return [
    ["Field", "Required", "Example", "Notes"],
    ["SKU", "No", "Auto Generated", "SKU is automatically generated by the system."],
    ["Product Name", "Yes", "Royal Canin Puppy", "Required field."],
    ["Category", "Yes", "Dog Food", "Use one of the allowed values from the dropdown list."],
    ["Price", "Yes", "450000", "Must be a number greater than or equal to 0."],
    ["Stock", "Yes", "24", "Must be a whole number greater than or equal to 0."],
    ["Status", "Yes", "ACTIVE", "Allowed values: ACTIVE, INACTIVE, OUT_OF_STOCK"],
    ["Description", "No", "Premium puppy food", "Optional field."],
  ];
}

async function exportProducts(products) {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Products");

  worksheet.columns = [
    { header: "SKU", key: "sku", width: 20 },
    { header: "Product Name", key: "name", width: 28 },
    { header: "Category", key: "category", width: 20 },
    { header: "Price", key: "price", width: 16 },
    { header: "Stock", key: "stock", width: 12 },
    { header: "Status", key: "status", width: 16 },
    { header: "Description", key: "description", width: 40 },
  ];

  worksheet.getRow(1).values = worksheet.columns.map((column) => column.header);
  worksheet.getRow(1).font = { bold: true };
  worksheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE5E7EB" } };

  products.forEach((product) => {
    worksheet.addRow({
      sku: product.sku ?? "",
      name: product.name ?? "",
      category: product.category ?? "",
      price: formatCurrency(product.price),
      stock: Number(product.stock ?? 0),
      status: product.status ?? "ACTIVE",
      description: product.description ?? "",
    });
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = EXCEL_EXPORT_FILE;
  link.click();
  window.URL.revokeObjectURL(url);
}

async function generateImportTemplate() {
  const workbook = new ExcelJS.Workbook();
  const productsSheet = workbook.addWorksheet("Products");
  const instructionsSheet = workbook.addWorksheet("Instructions");

  productsSheet.columns = [
    { header: "SKU", key: "sku", width: 20 },
    { header: "Product Name", key: "name", width: 28 },
    { header: "Category", key: "category", width: 20 },
    { header: "Price", key: "price", width: 16 },
    { header: "Stock", key: "stock", width: 12 },
    { header: "Status", key: "status", width: 16 },
    { header: "Description", key: "description", width: 40 },
  ];

  productsSheet.getRow(1).values = productsSheet.columns.map((column) => column.header);
  productsSheet.getRow(1).font = { bold: true };
  productsSheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE5E7EB" } };

  productsSheet.getColumn(1).eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE5E7EB" } };
    cell.protection = { locked: true };
  });

  productsSheet.getColumn(2).eachCell({ includeEmpty: true }, (cell) => {
    cell.protection = { locked: false };
  });
  productsSheet.getColumn(3).eachCell({ includeEmpty: true }, (cell) => {
    cell.protection = { locked: false };
  });
  productsSheet.getColumn(4).eachCell({ includeEmpty: true }, (cell) => {
    cell.protection = { locked: false };
  });
  productsSheet.getColumn(5).eachCell({ includeEmpty: true }, (cell) => {
    cell.protection = { locked: false };
  });
  productsSheet.getColumn(6).eachCell({ includeEmpty: true }, (cell) => {
    cell.protection = { locked: false };
  });
  productsSheet.getColumn(7).eachCell({ includeEmpty: true }, (cell) => {
    cell.protection = { locked: false };
  });

  productsSheet.protect("petshop", { selectLockedCells: true, selectUnlockedCells: true });

  const instructionRows = createInstructionRows();
  instructionsSheet.addRows(instructionRows);
  instructionsSheet.getRow(1).font = { bold: true };
  instructionsSheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE5E7EB" } };

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = TEMPLATE_FILE;
  link.click();
  window.URL.revokeObjectURL(url);
}

function parseWorkbookRows(worksheet) {
  const rows = [];

  worksheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber === 1) return;

    const values = row.values.slice(1);
    rows.push(values);
  });

  return rows;
}

function normalizeImportData(rawRows) {
  return rawRows
    .filter((row) => row.some((value) => value !== undefined && value !== null && String(value).trim() !== ""))
    .map((row) => ({
      sku: "",
      name: row[1] ?? "",
      category: normalizeCategory(row[2]),
      price: row[3],
      stock: row[4],
      status: normalizeStatus(row[5]),
      description: row[6] ?? "",
    }));
}

function validateProducts(rows, existingProducts = []) {
  const existingNames = new Set(existingProducts.map((product) => String(product.name).trim().toLowerCase()));
  const existingSkus = new Set(existingProducts.map((product) => String(product.sku).trim().toLowerCase()));

  const errors = [];
  const validRows = [];

  rows.forEach((row, index) => {
    const rowNumber = index + 2;
    const { name, category, price, stock, status } = row;

    const normalizedName = String(name ?? "").trim();
    const normalizedCategory = String(category ?? "").trim();
    const numericPrice = Number(price);
    const numericStock = Number(stock);

    if (!normalizedName) {
      errors.push({ row: rowNumber, message: "Product Name is required." });
      return;
    }

    if (!VALID_CATEGORIES.includes(normalizedCategory)) {
      errors.push({ row: rowNumber, message: "Category does not exist." });
      return;
    }

    if (!Number.isFinite(numericPrice) || numericPrice < 0) {
      errors.push({ row: rowNumber, message: "Price must be >= 0." });
      return;
    }

    if (!Number.isInteger(numericStock) || numericStock < 0) {
      errors.push({ row: rowNumber, message: "Stock must be a non-negative integer." });
      return;
    }

    if (!VALID_STATUSES.includes(status)) {
      errors.push({ row: rowNumber, message: "Status is invalid." });
      return;
    }

    const normalizedNameKey = normalizedName.toLowerCase();
    if (existingNames.has(normalizedNameKey)) {
      errors.push({ row: rowNumber, message: "Product Name duplicated." });
      return;
    }

    if (existingSkus.has(String(row.sku ?? "").trim().toLowerCase())) {
      errors.push({ row: rowNumber, message: "SKU duplicated." });
      return;
    }

    validRows.push({
      id: Date.now() + index,
      name: normalizedName,
      sku: `AUTO-${String(index + 1).padStart(3, "0")}`,
      category: normalizedCategory,
      price: numericPrice,
      stock: numericStock,
      status,
      description: String(row.description ?? "").trim(),
      image: "https://placehold.co/60x60",
    });
  });

  return { validRows, errors };
}

async function parseExcelFile(file) {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(file);
  const worksheet = workbook.getWorksheet("Products");

  if (!worksheet) {
    throw new Error("The Excel file must contain a Products sheet.");
  }

  const rows = parseWorkbookRows(worksheet);
  const normalizedRows = normalizeImportData(rows);

  return normalizedRows;
}

const productExcelService = {
  exportProducts,
  generateImportTemplate,
  parseExcelFile,
  validateProducts,
};

export default productExcelService;
